### ISSUE TITLE
ModuleNotFoundError: No module named 'distill_default_utils'

### ISSUE THREAD

**Issue by Shangui-zh** [silicx/LoRS_Distill#1]
Hello, nice work. 
While attempting to replicate your findings, I encountered a problem in the "buffer.py" file, line 6. It appears that a crucial module and function, "from distill_default_utils import load_or_process_file," are missing. I have been unable to locate this module elsewhere or determine the appropriate installation method. 
I kindly request your assistance in resolving this issue. Thank [you.]
<img width="1099" alt="missing module" src="https://github.com/silicx/LoRS_Distill/assets/76081566/b31e8cdd-9108-4a98-abd2-fc82a6eb7b19">

**Comment by silicx** [comment]
Hi! I'm sorry that the module `distill_default_utils` was moved to `src.vl_distill_utils`. Please try again with the latest `buffer.py`.

**Comment by Shangui-zh** [comment]
> Hi! I'm sorry that the module `distill_default_utils` was moved to `src.vl_distill_utils`. Please try again with the latest `buffer.py`.

Thank you.  Now I can run this.
